
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ayenun-100913999/$REPO_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ayenun-100913999/$REPO_NAME:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ayenun100913999 \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/ayenun-100913999/$REPO_NAME:$COMMIT_SHA \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
options:
  logging: 'CLOUD_LOGGING_ONLY'
  logStreamingOption: 'STREAM_ON'
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
